apiVersion: v1
kind: ConfigMap
metadata:
  name: admin-config
  namespace: travelhub

data:
  PORT: "4005"
  HOST: "0.0.0.0"

  AUTH_SERVICE_URL: "http://auth-service:4001"
  VUELOS_SERVICE_URL: "http://vuelos-service:4002"
  RESERVAS_SERVICE_URL: "http://reservas-service:4003"
  PAGOS_SERVICE_URL: "http://pagos-service:4004"