apiVersion: v1
kind: Service
metadata:
  name: admin-service
  namespace: travelhub

spec:
  selector:
    app: admin-service

  ports:
    - name: http
      port: 4005
      targetPort: 4005

  type: ClusterIP