apiVersion: v1
kind: Secret
metadata:
  name: postgres-reservas-secret
  namespace: travelhub

type: Opaque

stringData:
  POSTGRES_DB: travelhub_reservas
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: "23500"