apiVersion: v1
kind: ConfigMap
metadata:
  name: vuelos-config
  namespace: travelhub

data:
  PORT: "4002"
  HOST: "0.0.0.0"

  DB_HOST: "postgres-vuelos"
  DB_PORT: "5432"
  DB_NAME: "travelhub_vuelos"

  OTEL_SERVICE_NAME: "vuelos-service"
  OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: "http://otel-collector:4318/v1/traces"
  OTEL_TRACES_EXPORTER: "otlp"
  OTEL_PROPAGATORS: "tracecontext,baggage"