apiVersion: v1
kind: ConfigMap
metadata:
  name: pagos-config
  namespace: travelhub

data:
  PORT: "4004"
  HOST: "0.0.0.0"

  DB_HOST: "postgres-pagos"
  DB_PORT: "5432"
  DB_NAME: "travelhub_pagos"

  AUTH_SERVICE_URL: "http://auth-service:4001"
  RESERVAS_SERVICE_URL: "http://reservas-service:4003"

  OTEL_SERVICE_NAME: "pagos-service"
  OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: "http://otel-collector:4318/v1/traces"
  OTEL_TRACES_EXPORTER: "otlp"
  OTEL_PROPAGATORS: "tracecontext,baggage"