apiVersion: apps/v1
kind: Deployment
metadata:
  name: pagos-service
  namespace: travelhub

spec:
  replicas: 1

  selector:
    matchLabels:
      app: pagos-service

  template:
    metadata:
      labels:
        app: pagos-service

    spec:
      containers:
        - name: pagos-service

          image: travelhub-pagos:1.0
          imagePullPolicy: Never

          ports:
            - containerPort: 4004

          envFrom:
            - configMapRef:
                name: pagos-config

            - secretRef:
                name: pagos-secret

          readinessProbe:
            httpGet:
              path: /health
              port: 4004
            initialDelaySeconds: 5
            periodSeconds: 5

          livenessProbe:
            httpGet:
              path: /health
              port: 4004
            initialDelaySeconds: 20
            periodSeconds: 10