apiVersion: v1
kind: Secret
metadata:
  name: postgres-pagos-secret
  namespace: travelhub

type: Opaque

stringData:
  POSTGRES_DB: travelhub_pagos
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: "23500"