apiVersion: v1
kind: Secret
metadata:
  name: postgres-vuelos-secret
  namespace: travelhub
type: Opaque
stringData:
  POSTGRES_DB: travelhub_vuelos
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: "23500"